"ui.background" = { bg = "#ddd7c4" }
"ui.text" = { fg = "#393a34" }
"ui.text.focus" = { fg = "#393a34" }
"ui.cursor" = { fg = "#ddd7c4", bg = "#393a34" }
"ui.cursor.primary" = { fg = "#ddd7c4", bg = "#393a34" }
"ui.cursor.match" = { fg = "#ddd7c4", bg = "#2a6361" }
"ui.selection" = { bg = "#cac4b1" }
"ui.selection.primary" = { bg = "#b5b0a0" }
"ui.linenr" = { fg = "#8a8a80" }
"ui.linenr.selected" = { fg = "#393a34" }
"ui.cursorline.primary" = { bg = "#d2ccb9" }
"ui.statusline" = { fg = "#393a34", bg = "#d2ccb9" }
"ui.statusline.inactive" = { fg = "#8a8a80", bg = "#d5cfbc" }
"ui.statusline.normal" = { fg = "#ddd7c4", bg = "#33644d" }
"ui.statusline.insert" = { fg = "#ddd7c4", bg = "#854b3f" }
"ui.statusline.select" = { fg = "#ddd7c4", bg = "#2a6361" }
"ui.popup" = { fg = "#393a34", bg = "#d2ccb9" }
"ui.window" = { fg = "#c2bdad" }
"ui.help" = { fg = "#393a34", bg = "#d2ccb9" }
"ui.menu" = { fg = "#393a34", bg = "#d2ccb9" }
"ui.menu.selected" = { fg = "#393a34", bg = "#b5b0a0" }
"ui.menu.scroll" = { fg = "#8a8a80" }
"ui.virtual.whitespace" = { fg = "#c2bdad" }
"ui.virtual.ruler" = { bg = "#d2ccb9" }
"ui.virtual.indent-guide" = { fg = "#c2bdad" }
"ui.virtual.inlay-hint" = { fg = "#8a8a80" }
"ui.bufferline" = { fg = "#8a8a80", bg = "#d5cfbc" }
"ui.bufferline.active" = { fg = "#393a34", bg = "#ddd7c4" }

"comment" = { fg = "#515e51" }
"string" = { fg = "#854b3f" }
"string.special" = { fg = "#7f5031" }
"keyword" = { fg = "#33644d" }
"keyword.control" = { fg = "#8b4646" }
"keyword.control.return" = { fg = "#8b4646" }
"keyword.control.import" = { fg = "#515e51" }
"keyword.operator" = { fg = "#8b4646" }
"keyword.function" = { fg = "#33644d" }
"function" = { fg = "#426338" }
"function.method" = { fg = "#426338" }
"function.builtin" = { fg = "#426338" }
"function.macro" = { fg = "#8b4646" }
"variable" = { fg = "#6e5831" }
"variable.parameter" = { fg = "#5e5c23" }
"variable.builtin" = { fg = "#8b4646" }
"variable.other.member" = { fg = "#6e5831" }
"type" = { fg = "#2a6361" }
"type.builtin" = { fg = "#2a6361" }
"type.enum.variant" = { fg = "#2a6361" }
"constructor" = { fg = "#2a6361" }
"constant" = { fg = "#854b3f" }
"constant.numeric" = { fg = "#2e645d" }
"constant.character" = { fg = "#854b3f" }
"constant.character.escape" = { fg = "#8b4646" }
"constant.builtin" = { fg = "#6e5739" }
"constant.builtin.boolean" = { fg = "#6e5739" }
"operator" = { fg = "#8b4646" }
"punctuation" = { fg = "#5b5b54" }
"punctuation.delimiter" = { fg = "#5b5b54" }
"punctuation.bracket" = { fg = "#5b5b54" }
"punctuation.special" = { fg = "#8b4646" }
"tag" = { fg = "#2a6361" }
"attribute" = { fg = "#6e5831" }
"namespace" = { fg = "#2a6361" }
"label" = { fg = "#854b3f" }
"special" = { fg = "#8b4646" }

"markup.heading" = { fg = "#426338", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "#33644d", modifiers = ["underlined"] }
"markup.link.text" = { fg = "#854b3f" }
"markup.raw" = { fg = "#6e5831" }
"markup.raw.inline" = { fg = "#6e5831" }
"markup.list" = { fg = "#8b4646" }
"markup.normal" = { fg = "#393a34" }
"markup.normal.hover" = { fg = "#393a34" }
"markup.heading.hover" = { fg = "#426338", modifiers = ["bold"] }
"markup.raw.inline.hover" = { fg = "#6e5831" }
"markup.normal.completion" = { fg = "#393a34" }
"markup.heading.completion" = { fg = "#426338", modifiers = ["bold"] }
"markup.raw.inline.completion" = { fg = "#6e5831" }
"ui.popup.info" = { fg = "#393a34", bg = "#d2ccb9" }

"diff.plus" = { fg = "#33644d" }
"diff.minus" = { fg = "#8b4646" }
"diff.delta" = { fg = "#6e5831" }

"diagnostic.error" = { underline = { style = "curl", color = "#a23333" } }
"diagnostic.warning" = { underline = { style = "curl", color = "#6e5739" } }
"diagnostic.info" = { underline = { style = "curl", color = "#35616d" } }
"diagnostic.hint" = { underline = { style = "curl", color = "#515e51" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

"error" = { fg = "#a23333" }
"warning" = { fg = "#6e5739" }
"info" = { fg = "#35616d" }
"hint" = { fg = "#515e51" }
