"ui.background" = { bg = "#20231f" }
"ui.text" = { fg = "#dbd7ca" }
"ui.text.focus" = { fg = "#dbd7ca" }
"ui.cursor" = { fg = "#20231f", bg = "#dbd7ca" }
"ui.cursor.primary" = { fg = "#20231f", bg = "#dbd7ca" }
"ui.cursor.match" = { fg = "#20231f", bg = "#5da9a7" }
"ui.selection" = { bg = "#3a3a3a" }
"ui.selection.primary" = { bg = "#484540" }
"ui.linenr" = { fg = "#3a3a3a" }
"ui.linenr.selected" = { fg = "#dbd7ca" }
"ui.cursorline.primary" = { bg = "#282b25" }
"ui.statusline" = { fg = "#dbd7ca", bg = "#282b25" }
"ui.statusline.inactive" = { fg = "#585b51", bg = "#242721" }
"ui.statusline.normal" = { fg = "#20231f", bg = "#4d9375" }
"ui.statusline.insert" = { fg = "#20231f", bg = "#d29384" }
"ui.statusline.select" = { fg = "#20231f", bg = "#5da9a7" }
"ui.popup" = { fg = "#dbd7ca", bg = "#282b25" }
"ui.window" = { fg = "#383b33" }
"ui.help" = { fg = "#dbd7ca", bg = "#282b25" }
"ui.menu" = { fg = "#dbd7ca", bg = "#282b25" }
"ui.menu.selected" = { fg = "#e8e4da", bg = "#3a3a3a" }
"ui.menu.scroll" = { fg = "#585b51" }
"ui.virtual.whitespace" = { fg = "#383b33" }
"ui.virtual.ruler" = { bg = "#282b25" }
"ui.virtual.indent-guide" = { fg = "#383b33" }
"ui.virtual.inlay-hint" = { fg = "#606060" }
"ui.bufferline" = { fg = "#585b51", bg = "#242721" }
"ui.bufferline.active" = { fg = "#dbd7ca", bg = "#282b25" }

"comment" = { fg = "#7d857c" }
"string" = { fg = "#d29384" }
"string.special" = { fg = "#c99076" }
"keyword" = { fg = "#4d9375" }
"keyword.control" = { fg = "#cb7676" }
"keyword.control.return" = { fg = "#cb7676" }
"keyword.control.import" = { fg = "#7d857c" }
"keyword.operator" = { fg = "#8f8c84" }
"keyword.function" = { fg = "#4d9375" }
"function" = { fg = "#9aba7a" }
"function.method" = { fg = "#9aba7a" }
"function.builtin" = { fg = "#9aba7a" }
"function.macro" = { fg = "#cb7676" }
"variable" = { fg = "#bfae90" }
"variable.parameter" = { fg = "#b8a965" }
"variable.builtin" = { fg = "#cb7676" }
"variable.other.member" = { fg = "#bfae90" }
"type" = { fg = "#5da9a7" }
"type.builtin" = { fg = "#5da9a7" }
"type.enum.variant" = { fg = "#5da9a7" }
"constructor" = { fg = "#5da9a7" }
"constant" = { fg = "#c99076" }
"constant.numeric" = { fg = "#4c9a91" }
"constant.character" = { fg = "#d29384" }
"constant.character.escape" = { fg = "#cb7676" }
"constant.builtin" = { fg = "#c99076" }
"constant.builtin.boolean" = { fg = "#c99076" }
"operator" = { fg = "#8f8c84" }
"punctuation" = { fg = "#858585" }
"punctuation.delimiter" = { fg = "#858585" }
"punctuation.bracket" = { fg = "#858585" }
"punctuation.special" = { fg = "#8f8c84" }
"tag" = { fg = "#5da9a7" }
"attribute" = { fg = "#bd976a" }
"namespace" = { fg = "#5da9a7" }
"label" = { fg = "#d29384" }
"special" = { fg = "#8f8c84" }

"markup.heading" = { fg = "#9aba7a", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "#4d9375", modifiers = ["underlined"] }
"markup.link.text" = { fg = "#d29384" }
"markup.raw" = { fg = "#bd976a" }
"markup.raw.inline" = { fg = "#bd976a" }
"markup.list" = { fg = "#cb7676" }
"markup.normal" = { fg = "#dbd7ca" }
"markup.normal.hover" = { fg = "#dbd7ca" }
"markup.heading.hover" = { fg = "#9aba7a", modifiers = ["bold"] }
"markup.raw.inline.hover" = { fg = "#bd976a" }
"markup.normal.completion" = { fg = "#dbd7ca" }
"markup.heading.completion" = { fg = "#9aba7a", modifiers = ["bold"] }
"markup.raw.inline.completion" = { fg = "#bd976a" }
"ui.popup.info" = { fg = "#dbd7ca", bg = "#282b25" }

"diff.plus" = { fg = "#4d9375" }
"diff.minus" = { fg = "#cb7676" }
"diff.delta" = { fg = "#bd976a" }

"diagnostic.error" = { underline = { style = "curl", color = "#e05561" } }
"diagnostic.warning" = { underline = { style = "curl", color = "#e6cc77" } }
"diagnostic.info" = { underline = { style = "curl", color = "#6db3c2" } }
"diagnostic.hint" = { underline = { style = "curl", color = "#7d857c" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

"error" = { fg = "#e05561" }
"warning" = { fg = "#e6cc77" }
"info" = { fg = "#6db3c2" }
"hint" = { fg = "#7d857c" }
