"ui.background" = { bg = "#d5dace" }
"ui.text" = { fg = "#393a34" }
"ui.text.focus" = { fg = "#393a34" }
"ui.cursor" = { fg = "#d5dace", bg = "#393a34" }
"ui.cursor.primary" = { fg = "#d5dace", bg = "#393a34" }
"ui.cursor.match" = { fg = "#d5dace", bg = "#2b6361" }
"ui.selection" = { bg = "#b1b4aa" }
"ui.selection.primary" = { bg = "#bcc1b4" }
"ui.linenr" = { fg = "#80857a" }
"ui.linenr.selected" = { fg = "#393a34" }
"ui.cursorline.primary" = { bg = "#cbcfc4" }
"ui.statusline" = { fg = "#393a34", bg = "#cbcfc4" }
"ui.statusline.inactive" = { fg = "#80857a", bg = "#d2d6cb" }
"ui.statusline.normal" = { fg = "#d5dace", bg = "#34644d" }
"ui.statusline.insert" = { fg = "#d5dace", bg = "#864b3f" }
"ui.statusline.select" = { fg = "#d5dace", bg = "#2b6361" }
"ui.popup" = { fg = "#393a34", bg = "#cbcfc4" }
"ui.window" = { fg = "#bcc1b4" }
"ui.help" = { fg = "#393a34", bg = "#cbcfc4" }
"ui.menu" = { fg = "#393a34", bg = "#cbcfc4" }
"ui.menu.selected" = { fg = "#393a34", bg = "#a5a89e" }
"ui.menu.scroll" = { fg = "#80857a" }
"ui.virtual.whitespace" = { fg = "#bcc1b4" }
"ui.virtual.ruler" = { bg = "#cbcfc4" }
"ui.virtual.indent-guide" = { fg = "#bcc1b4" }
"ui.virtual.inlay-hint" = { fg = "#80857a" }
"ui.bufferline" = { fg = "#80857a", bg = "#d2d6cb" }
"ui.bufferline.active" = { fg = "#393a34", bg = "#d5dace" }

"comment" = { fg = "#666e65" }
"string" = { fg = "#7b3527" }
"string.special" = { fg = "#805031" }
"keyword" = { fg = "#34644d" }
"keyword.control" = { fg = "#8c4646" }
"keyword.control.return" = { fg = "#8c4646" }
"keyword.control.import" = { fg = "#666e65" }
"keyword.operator" = { fg = "#655c52" }
"keyword.function" = { fg = "#34644d" }
"function" = { fg = "#2f5419" }
"function.method" = { fg = "#2f5419" }
"function.builtin" = { fg = "#2f5419" }
"function.macro" = { fg = "#8c4646" }
"variable" = { fg = "#584d3a" }
"variable.parameter" = { fg = "#5e5c24" }
"variable.builtin" = { fg = "#8c4646" }
"variable.other.member" = { fg = "#584d3a" }
"type" = { fg = "#2b6361" }
"type.builtin" = { fg = "#2b6361" }
"type.enum.variant" = { fg = "#2b6361" }
"constructor" = { fg = "#2b6361" }
"constant" = { fg = "#805031" }
"constant.numeric" = { fg = "#2f645d" }
"constant.character" = { fg = "#7b3527" }
"constant.character.escape" = { fg = "#8c4646" }
"constant.builtin" = { fg = "#805031" }
"constant.builtin.boolean" = { fg = "#805031" }
"operator" = { fg = "#655c52" }
"punctuation" = { fg = "#5b5b54" }
"punctuation.delimiter" = { fg = "#5b5b54" }
"punctuation.bracket" = { fg = "#5b5b54" }
"punctuation.special" = { fg = "#655c52" }
"tag" = { fg = "#2b6361" }
"attribute" = { fg = "#6f5831" }
"namespace" = { fg = "#2b6361" }
"label" = { fg = "#7b3527" }
"special" = { fg = "#655c52" }

"markup.heading" = { fg = "#2f5419", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "#34644d", modifiers = ["underlined"] }
"markup.link.text" = { fg = "#7b3527" }
"markup.raw" = { fg = "#6f5831" }
"markup.raw.inline" = { fg = "#6f5831" }
"markup.list" = { fg = "#8c4646" }
"markup.normal" = { fg = "#393a34" }
"markup.normal.hover" = { fg = "#393a34" }
"markup.heading.hover" = { fg = "#2f5419", modifiers = ["bold"] }
"markup.raw.inline.hover" = { fg = "#6f5831" }
"markup.normal.completion" = { fg = "#393a34" }
"markup.heading.completion" = { fg = "#2f5419", modifiers = ["bold"] }
"markup.raw.inline.completion" = { fg = "#6f5831" }
"ui.popup.info" = { fg = "#393a34", bg = "#cbcfc4" }

"diff.plus" = { fg = "#34644d" }
"diff.minus" = { fg = "#8c4646" }
"diff.delta" = { fg = "#6f5831" }

"diagnostic.error" = { underline = { style = "curl", color = "#a33333" } }
"diagnostic.warning" = { underline = { style = "curl", color = "#7a6821" } }
"diagnostic.info" = { underline = { style = "curl", color = "#36616e" } }
"diagnostic.hint" = { underline = { style = "curl", color = "#666e65" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

"error" = { fg = "#a33333" }
"warning" = { fg = "#7a6821" }
"info" = { fg = "#36616e" }
"hint" = { fg = "#666e65" }
