# Patina Light theme for Alacritty

[colors.primary]
background = "#ddd7c4"
foreground = "#2e2a24"

[colors.cursor]
text = "#ddd7c4"
cursor = "#2e2a24"

[colors.selection]
text = "#2e2a24"
background = "#bfb8a3"

[colors.normal]
black = "#2e2a24"
red = "#9b3b3b"
green = "#34644c"
yellow = "#6e5817"
blue = "#2f626f"
magenta = "#7a4f47"
cyan = "#2e6260"
white = "#5a5248"

[colors.bright]
black = "#6a6258"
red = "#b64747"
green = "#3d764c"
yellow = "#81651a"
blue = "#3a7280"
magenta = "#8e5b51"
cyan = "#357270"
white = "#393a34"
